use_frameworks!

target 'AudioRecordingVisualizer_Example' do
  pod 'AudioRecordingVisualizer', :path => '../'

  target 'AudioRecordingVisualizer_Tests' do
    inherit! :search_paths

    
  end
end
